name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: .NET installieren
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Blazor WebAssembly veröffentlichen
        run: dotnet publish Portfolio/Portfolio/Portfolio.csproj -c Release --output dist

      - name: Deployment zu gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/wwwroot
